### ISSUE TITLE
执行都很正常  但是网页打不开

### ISSUE THREAD

**Issue by qingleer** [IDKiro/ssmgr-install#1]
执行都很正常  但是网页打不开  vultr 主机   换过N多IP

**Comment by IDKiro** [comment]
> 执行都很正常 但是网页打不开 vultr 主机 换过N多IP
新开的 Vultr centos7 是可以的，可能是你用了 Nginx 之类的。
不妨再开一台试试，vultr 主机按时计费也几乎没有成本。
