### ISSUE TITLE
呜呜呜大佬你好 我安装完了 怎么用呀

### ISSUE THREAD

**Issue by SoraKasvgano** [IDKiro/ssmgr-install#2]
呜呜呜大佬你好 我安装完了 怎么用呀

WEB界面在哪里可以打开呀 不会 呜呜呜

**Comment by yuger** [comment]
> 呜呜呜大佬你好 我安装完了 怎么用呀
> 
> WEB界面在哪里可以打开呀 不会 呜呜呜

@samondlee 我也不会，你会么？？

**Comment by IDKiro** [comment]
> > 呜呜呜大佬你好 我安装完了 怎么用呀
> > WEB界面在哪里可以打开呀 不会 呜呜呜
> 
> @samondlee 我也不会，你会么？？

默认装完是访问 http://IP:8080
