### ISSUE TITLE
centos 7 

### ISSUE THREAD

**Issue by lokisama** [IDKiro/ssmgr-install#3]
系统centos7
内核4.14.129
安装node报错

[Info] shadowsocks-libev-3.3.1.tar.gz [found]
[Info] libsodium-1.0.16.tar.gz [found]
[Info] mbedtls-2.6.0-gpl.tgz [found]
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/libsodium-1.0.16':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
[Error] libsodium-1.0.16 install failed.

起因：干净centos没有自带make gcc这种，
yum -y install gcc automake autoconf libtool make
yum install gcc gcc-c++

最后：安装后脚本不报错了

**Comment by IDKiro** [comment]
我在函数pre_install中有写这部分操作，可能不是这个问题。
