### ISSUE TITLE
邮箱类型如果选择others似乎会出现webgui.yml配置和官方wiki不一样

### ISSUE THREAD

**Issue by yodelife** [IDKiro/ssmgr-install#4]
首先感谢提供的脚本... 提前说明我是一小白，我不知道我提的这个算不算问题...
在您的一键脚本配置中，在邮箱类型的选择时，如果选择了Others（默认是mailgun），然后在webgui.yml中的email类型中就会出现（这里以163邮箱为例）
   email:
    use: true
    type: 'smtp'
    xxx@163.com: 'xxx@163.com'
    password: 'password'
    host: 'smtp.your-email.com'
作为参考，官方wiki给的格式是这样的
 email:
    use: true
    type: 'smtp'
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'

因为我发现这个问题后就删了，可能真实和我描述的有所出入。但是我印象中好像是，username变了...  不知道这个问题会不会导致错误？
另外，想问一下，mailgun服务中用免费的sandbox域名是可以发送验证码的吗？

**Comment by IDKiro** [comment]
两年前写的脚本，官方当然更新过了，对不上是正常的。
至于mailgun的问题，我忘了。

**Comment by yodelife** [comment]
哈哈哈好的  再次感谢解答！
